# Generated by Django 4.0.3 on 2024-05-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0001_initial'),
        ('Cart', '0002_alter_cart_products_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coupon.coupon'),
        ),
    ]
