# Generated by Django 4.0.3 on 2024-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cart_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ckecked',
            field=models.BooleanField(default=True),
        ),
    ]
