# Generated by Django 4.0.3 on 2024-06-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_cart_is_ckecked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_ckecked',
            new_name='is_checked',
        ),
    ]
