# Generated by Django 4.0.3 on 2024-03-10 06:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoryAndSubcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tags', models.CharField(max_length=100)),
                ('stock', models.CharField(choices=[('In Stock', 'In Stock'), ('On Sale', 'On Sale')], max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CategoryAndSubcategory.category')),
                ('Sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CategoryAndSubcategory.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_imgs', to='Products.product')),
            ],
        ),
    ]
