# Generated by Django 4.0.3 on 2024-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryAndSubcategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(related_name='categories', to='CategoryAndSubcategory.subcategory'),
        ),
    ]
