# Generated by Django 4.0.3 on 2024-06-29 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customerSection', '0001_initial'),
        ('Cart', '0006_rename_is_ckecked_cart_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Full Payment', 'Full Payment'), ('Paypal', 'Paypal')], default='Full Payment', max_length=50)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='Processing', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_partial_cod_remain_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partial_cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('for_order_confirmation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_applied', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coupon.coupon')),
                ('order_items', models.ManyToManyField(to='Cart.cart')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerSection.customershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
