# Generated by Django 4.0.3 on 2024-06-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
