# Generated by Django 4.0.3 on 2024-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbillingaddress',
            name='customization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='customization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
